package Text_example;

import java.util.logging.Level;

import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author Xu xingrui
 */
public class Test extends javax.swing.JFrame {


	/**
	 * Creates new form NewJFrame
	 */



	public Test() {
		initComponents();
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {


		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jButton0 = new javax.swing.JButton();
		jButtondot = new javax.swing.JButton();
		jButtonadd = new javax.swing.JButton();
		jButtonsub = new javax.swing.JButton();
		jButtonmulp = new javax.swing.JButton();
		jButtondiv = new javax.swing.JButton();
		jButtonequal = new javax.swing.JButton();
		jButtonclear = new javax.swing.JButton();
		jButtonback = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("计算器");
		setResizable(false);


		jPanel1.setOpaque(false);
		jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));


		jButton1.setText("1");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton1MouseReleased(evt);
			}
		});


		jTextField1.setEditable(false);
		jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		jTextField1.setText("0");


		jButton2.setText("2");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton2MouseReleased(evt);
			}
		});


		jButton3.setText("3");
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton3MouseReleased(evt);
			}
		});


		jButton4.setText("4");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton4MouseReleased(evt);
			}
		});


		jButton5.setText("5");
		jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton5MouseReleased(evt);
			}
		});


		jButton6.setText("6");
		jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton6MouseReleased(evt);
			}
		});


		jButton7.setText("7");
		jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton7MouseReleased(evt);
			}
		});


		jButton8.setText("8");
		jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton8MouseReleased(evt);
			}
		});


		jButton9.setText("9");
		jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton9MouseReleased(evt);
			}
		});


		jButton0.setText("0");
		jButton0.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton0MouseReleased(evt);
			}
		});


		jButtondot.setText(".");
		jButtondot.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtondotMouseReleased(evt);
			}
		});


		jButtonadd.setText("+");
		jButtonadd.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonaddMouseReleased(evt);
			}
		});


		jButtonsub.setText("-");
		jButtonsub.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonsubMouseReleased(evt);
			}
		});


		jButtonmulp.setText("*");
		jButtonmulp.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonmulpMouseReleased(evt);
			}
		});


		jButtondiv.setText("/");
		jButtondiv.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtondivMouseReleased(evt);
			}
		});


		jButtonequal.setText("=");
		jButtonequal.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonequalMouseReleased(evt);
			}
		});


		jButtonclear.setText("C");
		jButtonclear.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonclearMouseReleased(evt);
			}
		});


		jButtonback.setText("CE");
		jButtonback.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButtonbackMouseReleased(evt);
			}
		});


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(11, 11, 11)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGap(35, 35, 35)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jButton4)
																				.addGap(18, 18, 18)
																				.addComponent(jButton5)
																				.addGap(18, 18, 18)
																				.addComponent(jButton6))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jButton1)
																				.addGap(18, 18, 18)
																				.addComponent(jButton2)
																				.addGap(18, 18, 18)
																				.addComponent(jButton3))
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addComponent(jButton7)
																				.addGap(18, 18, 18)
																				.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(18, 18, 18)
																				.addComponent(jButton9)))
																.addGap(18, 18, 18)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jButtondiv)
																		.addComponent(jButtonmulp)
																		.addComponent(jButtonsub)))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18)
																.addComponent(jButtondot)
																.addGap(18, 18, 18)
																.addComponent(jButtonadd)))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
														.addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButtonequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(35, 35, 35))
		);


		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonadd, jButtonback, jButtonclear, jButtondiv, jButtondot, jButtonequal, jButtonmulp, jButtonsub});


		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGap(33, 33, 33)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtondiv)
												.addComponent(jButtonclear))
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton7)
												.addComponent(jButton8)
												.addComponent(jButton9)))
								.addGap(14, 14, 14)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
										.addComponent(jButtonback)
										.addComponent(jButtonmulp)
										.addComponent(jButton4)
										.addComponent(jButton5)
										.addComponent(jButton6))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jButton2)
																.addComponent(jButton3)
																.addComponent(jButtonsub))
														.addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jButtonadd)
																.addComponent(jButtondot))))
										.addComponent(jButtonequal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34))
		);


		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton0, jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonadd, jButtonback, jButtonclear, jButtondiv, jButtondot, jButtonmulp, jButtonsub});


		jPanel3.setPreferredSize(new java.awt.Dimension(400, 300));


		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test1/捕获.PNG"))); // NOI18N
		jLabel2.setMaximumSize(new java.awt.Dimension(400, 300));
		jLabel2.setMinimumSize(new java.awt.Dimension(400, 300));
		jLabel2.setPreferredSize(new java.awt.Dimension(400, 300));


		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 400, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 320, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
		);


		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
		jLayeredPane1.setLayout(jLayeredPane1Layout);
		jLayeredPane1Layout.setHorizontalGroup(
				jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
						.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
		);
		jLayeredPane1Layout.setVerticalGroup(
				jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jLayeredPane1Layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
		);
		jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);


		jPanel3.getAccessibleContext().setAccessibleDescription("");


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);


		pack();
	}// </editor-fold>


	public static int f=0;//记录最后一位的状态
	public boolean flag=true;//记录=的状态
	public static int dot=0;//记录小数点状态
	public int check(){//判断最后一位
		String str=jTextField1.getText();
		char c=str.charAt(str.length()-1);

		if(c=='+') {
			f= 1;

		} else if(c=='-'){
			f= 2;
		} else if(c=='*'){
			f= 3;
		} else if(c=='/'){
			f= 4;
		}
//        jButtonequal.setText(""+f);
		return f;
	}

	private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//jTextField1.setText("Hello World!");
		setNum("1");
		f=0;
	}


	public void setNum(String str){//通用
		String str1=jTextField1.getText();
		if(str1.equals("0")||!flag){
			jTextField1.setText(str.toString());
			flag=true;
		}
		else if(flag){
			jTextField1.setText(str1+str);
		}

	}

	private void jButton0MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("0");
		f=0;
	}


	private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("2");
		f=0;
	}


	private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("3");
		f=0;
	}


	private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("4");
		f=0;
	}


	private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("5");
		f=0;
	}


	private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("6");
		f=0;
	}


	private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("7");
		f=0;
	}


	private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("8");
		f=0;
	}


	private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		setNum("9");
		f=0;
	}
	//加号
	private void jButtonaddMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String str=jTextField1.getText();
		if(str.equals("0")){setNum("0+");}
		if(!flag){setNum(str+"+");flag=true;}
		else{
			if(check()==0){setNum("+");}
			else if(check()!=1){
				back();
				setNum("+");
			}
		}
		dot=0;
	}
	//减号
	private void jButtonsubMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String str=jTextField1.getText();
		if(str.equals("0")){setNum("0-");}
		if(!flag){setNum(str+"-");flag=true;}
		else{
			if(check()==0){setNum("-");}
			else if(check()!=2){
				back();
				setNum("-");
			}
		}
		dot=0;


	}
	//乘号
	private void jButtonmulpMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String str=jTextField1.getText();
		if(str.equals("0")){setNum("0*");}
		if(!flag){setNum(str+"*");flag=true;}
		else{
			if(check()==0){setNum("*");}
			else if(check()!=3){
				//            jButtondot.setText("3");
				back();
				setNum("*");
			}
		}
		dot=0;


	}
	//除号
	private void jButtondivMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String str=jTextField1.getText();
		if(str.equals("0")){setNum("0/");}
		if(!flag){setNum(str+"/");flag=true;}
		else{
			if(check()==0){setNum("/");}
			else if(check()!=4){
				back();
				setNum("/");
			}
		}
		dot=0;
	}
	//等号
	private void jButtonequalMouseReleased(java.awt.event.MouseEvent evt) {
		try {
			// TODO add your handling code here:
			if(check()!=0)back();
			f=0;
			dot=0;
			ScriptEngineManager manager=new ScriptEngineManager();
			ScriptEngine se =manager.getEngineByName("js");
			Double result=(Double)se.eval("("+jTextField1.getText()+")*1.0");
			jTextField1.setText(result.toString());
			flag=false;
		} catch (ScriptException ex) {
		}
	}
	//清除
	private void jButtonclearMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("0");
		dot=0;
	}
	//退格
	private void jButtonbackMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if(flag){
			back();
		}
		else jTextField1.setText("0");
	}
	//小数点
	private void jButtondotMouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		String str=jTextField1.getText();
		if(str.equals("0")){dot=1;setNum("0.");}
		if(check()!=0){dot=1;setNum("0.");}
		if(dot==0){dot=1;setNum(".");}
	}


	public void back(){//退格通用
		String str=jTextField1.getText();
		StringBuffer strBuff=new StringBuffer(str);
		if(str.charAt(str.length()-1)=='.'){dot=0;}
		if(str.length()<2){jTextField1.setText("0");}
		else {
			strBuff.deleteCharAt(str.length()-1);
			jTextField1.setText(strBuff.toString());
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
		} catch (InstantiationException ex) {
		} catch (IllegalAccessException ex) {
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		}
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
			}
		});
	}


	// Variables declaration - do not modify
	private javax.swing.JButton jButton0;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JButton jButtonadd;
	private javax.swing.JButton jButtonback;
	private javax.swing.JButton jButtonclear;
	private javax.swing.JButton jButtondiv;
	private javax.swing.JButton jButtondot;
	private javax.swing.JButton jButtonequal;
	private javax.swing.JButton jButtonmulp;
	private javax.swing.JButton jButtonsub;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration
}
